services:
  db:
    image: postgres:15
    container_name: crust_me
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springpass
      POSTGRES_DB: pizzaria
    ports:
      - "5432:5432"
    volumes:
      - pizzaria-data:/var/lib/postgresql/data

volumes:
  pizzaria-data: